Repository ReXume/techeer-resume, pull requests merged in 2024-09, with the labels that each got.

#6 Chore/#5 모노레포를 위한 수정 작업
  .gitignore
  backend/.gitignore
  backend/build.gradle
  backend/docker-compose.yml
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/techeer/backend/BackendApplication.java
  backend/src/main/java/com/techeer/backend/global/common/BaseEntity.java
  backend/src/main/java/com/techeer/backend/global/config/SwaggerConfig.java
  backend/src/main/java/com/techeer/backend/global/config/WebConfig.java
  backend/src/main/java/com/techeer/backend/global/error/ErrorCode.java
  backend/src/main/java/com/techeer/backend/global/error/ErrorResponse.java
  backend/src/main/java/com/techeer/backend/global/error/GlobalExceptionHandler.java
  backend/src/main/java/com/techeer/backend/global/error/exception/BusinessException.java
  backend/src/main/java/com/techeer/backend/global/success/SuccessCode.java
  backend/src/main/java/com/techeer/backend/global/success/SuccessResponse.java
  backend/src/main/resources/application.properties
  backend/src/test/java/com/techeer/backend/BackendApplicationTests.java
  settings.gradle
Labels: 🧭 Chore

#8 chore: 프론트엔드 초기세팅
  frontend/.gitignore
  frontend/.prettierrc
  frontend/README.md
  frontend/eslint.config.js
  frontend/index.html
  frontend/package.json
  frontend/postcss.config.js
  frontend/public/vite.svg
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/react.svg
  frontend/src/index.css
  frontend/src/main.tsx
  frontend/src/vite-env.d.ts
  frontend/tailwind.config.js
  frontend/tsconfig.app.json
  frontend/tsconfig.json
  frontend/tsconfig.node.json
  frontend/vite.config.ts
  frontend/yarn.lock
Labels: 🧭 Chore

#10 Create CODEOWNERS
  .github/CODEOWNERS
Labels: 🧭 Chore

#12 docs : 리드미 수정
  README.md
Labels: 📑 Docs

#14 chore : 코드 리뷰어 재설정
  .github/CODEOWNERS
Labels: 🧭 Chore

#26 [Design/#22] 네비게이션 바 구성
  frontend/index.html
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/logo.svg
  frontend/src/assets/profile.svg
  frontend/src/components/Navbar.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/index.css
  frontend/src/pages/MainPage.tsx
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: 🎨Design

#46 pr_template 수정
  .github/pull_request_template.md
Labels: 📑 Docs

#49 [chore] S3 연결
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/techeer/backend/BackendApplication.java
  backend/src/main/java/com/techeer/backend/global/config/AmazonS3Config.java
  backend/src/main/resources/application.properties
Labels: 🧭 Chore

#40 [feat] 이력서 등록 API
  backend/.gitignore
  backend/docker-compose.yml
  backend/src/main/java/com/techeer/backend/domain/resume/controller/ResumeController.java
  backend/src/main/java/com/techeer/backend/domain/resume/dto/request/CreateResumeReq.java
  backend/src/main/java/com/techeer/backend/domain/resume/entity/Resume.java
  backend/src/main/java/com/techeer/backend/domain/resume/repository/ResumeRepository.java
  backend/src/main/java/com/techeer/backend/domain/resume/service/ResumeService.java
  backend/src/main/java/com/techeer/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/techeer/backend/domain/user/entity/Role.java
  backend/src/main/java/com/techeer/backend/domain/user/entity/User.java
  backend/src/main/java/com/techeer/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/techeer/backend/domain/user/service/UserService.java
  backend/src/main/java/com/techeer/backend/global/config/MultipartJackson2HttpMessageConverter.java
  backend/src/main/resources/application.properties
Labels: 🚀 Feat

#56 feat/#51 모니터링 툴 구축 및 docker compose 작성
  .github/workflows/codereview.yml
  backend/.gitignore
  backend/Dockerfile-develop
  backend/docker-compose.deploy.yml
  backend/docker-compose.yml
  backend/newrelic-infra.dockerfile
  backend/newrelic-infra/newrelic-infra.yml
  backend/src/main/resources/application.properties
  backend/src/main/resources/application.yml
  backend/wait-for-it.sh
Labels: 🚀 Feat

#48 [design] 메인페이지 퍼블리싱 완료
  frontend/index.html
  frontend/src/App.css
  frontend/src/App.tsx
  frontend/src/assets/ArrowDown.svg
  frontend/src/assets/avatar.png
  frontend/src/assets/baggage3.svg
  frontend/src/assets/man1.png
  frontend/src/assets/man2.png
  frontend/src/assets/pngegg2.svg
  frontend/src/components/MainPage/BannerCard.tsx
  frontend/src/components/MainPage/Category.tsx
  frontend/src/components/Navbar.tsx
  frontend/src/components/PostCard.tsx
  frontend/src/pages/MainPage.tsx
  frontend/tailwind.config.js
Labels: 🎨Design

#60 feat/#57 태그 조회 api 구현 및 전체적인 수정
  backend/src/main/java/com/techeer/backend/domain/feedback/Repository/FeedbackRepository.java
  backend/src/main/java/com/techeer/backend/domain/feedback/Service/FeedbackService.java
  backend/src/main/java/com/techeer/backend/domain/feedback/controller/FeedbackController.java
  backend/src/main/java/com/techeer/backend/domain/feedback/dto/FeedbackCreateRequest.java
  backend/src/main/java/com/techeer/backend/domain/feedback/dto/FeedbackResponse.java
  backend/src/main/java/com/techeer/backend/domain/feedback/entity/Feedback.java
  backend/src/main/java/com/techeer/backend/domain/resume/controller/ResumeController.java
  backend/src/main/java/com/techeer/backend/domain/resume/dto/request/CreateResumeRequest.java
  backend/src/main/java/com/techeer/backend/domain/resume/dto/request/ResumeSearchRequest.java
  backend/src/main/java/com/techeer/backend/domain/resume/dto/response/ResumeResponse.java
  backend/src/main/java/com/techeer/backend/domain/resume/entity/Position.java
  backend/src/main/java/com/techeer/backend/domain/resume/entity/Resume.java
  backend/src/main/java/com/techeer/backend/domain/resume/entity/ResumeTechStack.java
  backend/src/main/java/com/techeer/backend/domain/resume/entity/TechStack.java
  backend/src/main/java/com/techeer/backend/domain/resume/repository/GetResumeRepository.java
  backend/src/main/java/com/techeer/backend/domain/resume/repository/ResumeRepository.java
  backend/src/main/java/com/techeer/backend/domain/resume/repository/ResumeSpecification.java
  backend/src/main/java/com/techeer/backend/domain/resume/service/ResumeService.java
  backend/src/main/java/com/techeer/backend/domain/user/controller/UserController.java
  backend/src/main/java/com/techeer/backend/domain/user/entity/Role.java
  backend/src/main/java/com/techeer/backend/domain/user/entity/User.java
  backend/src/main/java/com/techeer/backend/domain/user/repository/UserRepository.java
  backend/src/main/java/com/techeer/backend/domain/user/service/UserService.java
  backend/src/main/java/com/techeer/backend/feedback/Repository/ResumeRepository.java
  backend/src/main/java/com/techeer/backend/feedback/entity/Resume.java
Labels: 🧹 Refactor

#68 [feat] 여러 이력서 조회 API
  backend/src/main/java/com/techeer/backend/api/resume/controller/ResumeController.java
  backend/src/main/java/com/techeer/backend/api/resume/dto/response/ResumePageElement.java
  backend/src/main/java/com/techeer/backend/api/resume/dto/response/ResumePageResponse.java
  backend/src/main/java/com/techeer/backend/api/resume/repository/ResumeRepository.java
  backend/src/main/java/com/techeer/backend/api/resume/service/ResumeService.java
Labels: 🚀 Feat, Backend

#71 [feat] spring security를 이용한 회원가입
  backend/build.gradle
  backend/src/main/java/com/techeer/backend/api/user/config/SecurityConfig.java
  backend/src/main/java/com/techeer/backend/api/user/controller/UserController.java
  backend/src/main/java/com/techeer/backend/api/user/domain/Role.java
  backend/src/main/java/com/techeer/backend/api/user/domain/User.java
  backend/src/main/java/com/techeer/backend/api/user/dto/request/UserRegisterRequest.java
  backend/src/main/java/com/techeer/backend/api/user/repository/UserRepository.java
  backend/src/main/java/com/techeer/backend/api/user/service/UserService.java
Labels: 🧭 Chore, 🚀 Feat, Backend

#74 [design] 검색결과 페이지 퍼블리싱 완료
  frontend/package.json
  frontend/src/App.tsx
  frontend/src/assets/chevron-down.svg
  frontend/src/assets/search-normal.svg
  frontend/src/components/Navbar.tsx
  frontend/src/components/Search/CareerModal.tsx
  frontend/src/components/Search/PositionModal.tsx
  frontend/src/components/Search/Slider.tsx
  frontend/src/components/resumeoverview/ETC.tsx
  frontend/src/pages/MainPage.tsx
  frontend/src/pages/ResumeFeedbackPage.tsx
  frontend/src/pages/SearchPage.tsx
  frontend/src/pages/Upload.tsx
  frontend/src/store/CategoryStore.ts
  frontend/tailwind.config.js
  frontend/yarn.lock
Labels: 🎨Design
